version: '3'

services:
  broker:
    image: eclipse-mosquitto:2.0
    volumes:
      - "./mosquitto:/mosquitto"
    networks:
      - netBroker
    ports:
      - "1883:1883"

  telegraf:
    hostname: telegraf-smartiot
    image: telegraf:1.18.3
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influx
      - broker
    networks:
      - netInflux
      - netBroker

  influx:
    hostname: influx-smartiot
    image: influxdb:1.8
    volumes:
      - influxdb-smartiot-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=smartIoT
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    networks:
      - netInflux

  grafana:
    hostname: grafana-smartiot
    image: grafana/grafana:7.3.7
    networks:
      - netInflux
    ports:
      - 3000:3000
    depends_on:
      - influx
    volumes:
      - grafana-smartiot-data:/var/lib/grafana

volumes:
  grafana-smartiot-data:
  influxdb-smartiot-data:
networks:
  netInflux:
  netBroker:
